zhbit_wiki_wechat:
    resource: "@ZhbitWIKIWechatBundle/Controller/"
    type:     annotation
    prefix:   /

zhbit_wiki_common:
    resource: "@ZhbitWIKICommonBundle/Controller/"
    type:     annotation
    prefix:   /





