services:
    #Factory
    zhbitwiki_wechat.factory.easywechat_factory:
        class: ZhbitWIKI\WechatBundle\Factory\EasyWeChatFactory

    #Extension
    zhbitwiki_wechat.extension.wechat.sdk:
        class: EasyWeChat\Foundation\Application
        factory: [ "@zhbitwiki_wechat.factory.easywechat_factory", createNewInstance ]
        arguments: [ "@logger", '' ]
        tags:
            - { name: monolog.logger, channel: wechat }

    #Security
    zhbitwiki_wechat.security.wechat_provider:
        class: ZhbitWIKI\WechatBundle\Security\Authentication\Provider\WechatProvider
        arguments: [ "%wechat.user_class%", '@doctrine.orm.default_entity_manager' ]

    zhbitwiki_wechat.security.wechat_listener:
        class: ZhbitWIKI\WechatBundle\Security\Firewall\WechatListener
        arguments:
            - [ "@security.token_storage" ]
            - [ "@security.authentication.manager" ]
            - [ "@security.http_utils" ]
            - [ "@zhbitwiki_wechat.extension.wechat.sdk" ]
            - [ "@event_dispatcher" ]


