services:
    #Factory
    zhbitwiki_wechat.factory.easywechat_factory:
        class: ZhbitWIKI\WechatBundle\Factory\EasyWeChatFactory

    #Extension
    zhbitwiki_wechat.extension.wechat.sdk:
        class: ZhbitWIKI\WechatBundle\DependencyInjection\WechatExtension
        factory: [ "@zhbitwiki_wechat.factory.easywechat_factory", createNewInstance ]
        arguments: [ "logger" ]
        tags:
            - { name: monolog.logger, channel: wechat }